- src/App.js
- src/pages/Login.js
> [GRUPO 8] [Projeto Trivia] 💯 🚀 

- src/App.js
- src/index.js
- src/pages/home.js
- src/reducer/index.js
- src/reducer/user.js
- src/store/index.js
-primeiro requisito finalizado /o/
> first requirement is done

- package-lock.json
- package.json
- src/App.js
- src/Home.js
- src/components/Header.js
- src/components/Questions.js
- src/index.js
- src/pages/Jogo.js
- src/pages/Login.js
- src/pages/Settings.js
- src/services/token.js
Subindo requisitos feitos em 13/06 - teste
> [PROJETO TRIVIA] [GRUPO 13]

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/components/API
- src/components/Form.js
- src/index.js
- src/pages/Feedback.js
- src/pages/Game.js
- src/pages/Login.js
- src/pages/Ranking.js
- src/reducers/apiReducer.js
- src/reducers/index.js
- src/reducers/playerReducer.js
- src/store/index.js
Bora 🚀 🚀 🚀 🚀  começar mais um projeto
> [Grupo 9] [Projeto Trivia React Redux]

- package-lock.json
- package.json
- src/App.js
- src/actions/index.js
- src/components/Login.js
- src/index.js
- src/reducers/index.js
- src/reducers/login.js
- src/store/index.js
> [GRUPO 26] Requisito 1 completo

- README.md
- package-lock.json
- package.json
- src/App.js
- src/components/Inputs.jsx
- src/index.js
- src/pages/Login.jsx
- src/redux/reducers/initialState.js
- src/redux/reducers/reducer.js
- src/redux/store/index.js
> Grupo 22 requisito 1

- src/App.js
- src/components/Home.js
- src/index.js
- src/pages/Configs.js
- src/pages/Login.js
> [Grupo 8] - Requisito 03

- package-lock.json
- package.json
- src/App.js
- src/index.js
- src/pages/Login.js
- src/reducers/index.js
- src/reducers/triviaGame.js
- src/store/index.js
First commit by the best Group :)
> [Group 10] [Req 01]

- src/App.js
- src/pages/Config.js
- src/pages/Login.js
Requisito 3 com erro de beforeEach
> Main group 17 req 3

- src/App.js
- src/pages/Login.js
- src/pages/Settings.js
> [Group 10] [Req 3]

- src/Actions/index.js
- src/App.js
- src/Pages/home.js
- src/Pages/play.js
- src/Reducers/index.js
- src/Reducers/login.js
- src/Services/API.js
> Main group 25 req2

- package-lock.json
- package.json
- src/pages/Login.jsx
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/playerReducer.js
- src/redux/store/index.js
Save login infos in the Redux store.
> [Group 23][Req 1 Redux]

- package-lock.json
- package.json
- src/actions/index.js
- src/index.js
- src/pages/Login.js
- src/reducers/index.js
- src/reducers/login.js
- src/store/index.js
> [Requisito 2] [Grupo 1]

- package-lock.json
- src/App.js
- src/actions/gravatarAction.js
- src/actions/index.js
- src/components/HeaderGame.js
- src/pages/GamePlay.js
- src/pages/Login.js
- src/reducers/triviaGame.js
> Feat: Start Req 4

- src/App.js
- src/components/Inputs.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/redux/action/index.js
> [Main group-22][requisito-4]

- package-lock.json
- package.json
- src/App.js
- src/redux/actions/player.js
- src/redux/reducers/index.js
- src/redux/reducers/player.js
- src/redux/store/index.js
> [GRUPO 33] Req-00

- src/App.js
- src/components/ButtonSettings.js
- src/components/Login.js
- src/pages/Settings.js
> Main Group 26 - Requisito 3

- src/pages/Game.jsx
- src/pages/Login.jsx
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/questReducer.js
- src/services/api/getTriviaQuestions.js
Finalização da chamada da API & modificações do thunk
> [Main group 20][Req-05][Andamento]

- src/pages/Feedback.jsx
feedback page created, including requirements 12, 13 and 14
> [feat][reqs 12, 13 and 14]

- src/components/Cronometro.js
- src/components/Questions.js
- src/pages/Jogo.js
> Main group 13 requisito 10

- src/components/PerguntaAtual.js
- src/pages/Jogo.js
> GRUPO 16 - REQ10

- cypress/integration/project.spec.js
- src/actions/index.js
- src/pages/Feedback.jsx
- src/pages/FeedbackHeader.jsx
- src/reducers/player.js
requisitos 1 a 15 para estar funcionando e passando
> Main group 34 req 14

- src/App.js
- src/components/GameHeader.jsx
- src/components/LoginForm.jsx
- src/pages/GamePage.js
Criando header da página de jogar
> Main group 31 - game header

- src/components/Questions.jsx
> [Group 3] [Req 10]

- src/App.js
- src/components/Questions.js
- src/pages/Feedback.js
> [GRUPO 13] Teste requisito 12

- src/actions/index.js
- src/components/Answers.js
- src/pages/GamePage.js
- src/pages/GamePlay.js
- src/pages/Login.js
- src/reducers/triviaGame.js
> [Group 10] [Req 5]

- src/components/Game.js
- src/components/Timer.js
- src/reducers/index.js
- src/reducers/timeout.js
> [main-group-26-requisito-8]

- src/App.css
- src/action/index.js
- src/components/Timer.jsx
- src/pages/TriviaGame.jsx
- src/reducers/player.js
show player score when a correct answer are selected. Save current score on localStorage and global state.
> [Grupo 15 ] Req 9 - show player score when a correct answer are selected.

- src/components/Cronometer.js
- src/components/Question.js
> [Requisito 8] Grupo 01

- src/App.js
- src/components/FeedBackHeader.jsx
- src/components/FeedBackMain.jsx
- src/pages/FeedBackPage.js
A página de feedback requisitos 12 e 13 / falta aplicar que ela retorne apos todas as perguntas serem respondidas
> Group 31 Requisito 12/13

- src/components/Quiz.js
- src/components/Timer.js
- src/reducers/timeout.js
> iniciando correções do requisito 8

- src/pages/Game.jsx
> [Main group 22] [req 10]

- cypress/integration/project.spec.js
- src/pages/Feedback.js
- src/pages/Game.js
**PRIORIDADE 3** - A pessoa terá a opção "Jogar novamente", que ao ser clicada, levará para a tela de inicial
* Ao clicar no botão "Jogar novamente", a pessoa deve ser redirecionada para a tela de início (login)
* O botão para jogar novamente deve possuir o atributo `data-testid` com o valor `btn-play-again`
**O que será avaliado**
* A pessoa deve ser redirecionada para tela inicial
FIGMA: https://www.figma.com/file/9XUqIwKEFBfbZn5t8MMZJY/Trivia---project?node-id=0%3A1
> Inicio do requisito 15

- cypress/integration/project.spec.js
- src/App.js
- src/components/MsgFeedback.js
- src/pages/Feedback.js
> Main group 26 requisito 13

- src/components/Answers.js
- src/pages/GamePlay.js
- src/reducers/triviaGame.js
> [Group 10] [Req 11]

- src/components/Timer.jsx
- src/pages/Game.jsx
- src/pages/css/Game.css
> [GRUPO 33] Req07

- src/components/FeedbackMessage.jsx
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/redux/actions/index.js
- src/redux/reducers/questReducer.js
> Main group 20 req14

- src/components/FeedbackMessage.jsx
- src/pages/Feedback.jsx
> Main group 20 req13

- cypress/integration/project.spec.js
- src/actions/correctAnswer.js
- src/actions/gameAction.js
- src/components/API
- src/components/Answer.js
- src/components/Header.js
- src/components/Timer.js
- src/pages/Feedback.js
- src/pages/Game.js
- src/reducers/gameReduce.js
- src/reducers/index.js
- src/reducers/playerReducer.js
> [GRUPO 9][REQUISITO 11]

- src/App.css
- src/GamePageCss.css
- src/pages/GamePage.jsx
> [Group 4] Main group 4 req 7 carlos vieira

- src/components/Timer.jsx
- src/pages/Game.jsx
- src/redux/actions/game.js
- src/redux/reducers/game.js
- src/redux/reducers/player.js
> [GRUPO 33] Req-08

- src/components/Answer.js
- src/components/Timer.js
- src/pages/Feedback.js
- src/pages/Game.js
- src/reducers/playerReducer.js
> [GRUPO 9][REQUISITO 12]

- src/components/Answer.js
- src/components/Timer.js
- src/pages/Feedback.js
- src/pages/Game.js
- src/reducers/playerReducer.js
> [GRUPO 9] [REQUISITO13]

- src/pages/Game.jsx
- src/redux/actions/index.js
- src/services/helpers/randomizeRes.js
Finalizado dança das alternativas
> BUG: corrigido samba das alternativas

- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/redux/actions/player.js
- src/redux/reducers/player.js
> [GRUPO 33] Req 14 / 15

- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/redux/actions/player.js
- src/redux/reducers/player.js
> [GRUPO] Req 13

- src/components/Card.jsx
- src/components/CardList.jsx
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/redux/actions/game.js
- src/redux/reducers/game.js
> [GRUPO 33] Req 17
